// frontend/app/page.tsx

import { Brain, Network, TrendingUp, Target, Users, RefreshCw } from 'lucide-react'
import ArchitectureDiagram from '@/components/home/ArchitectureDiagram'

export default function Home() {
  const highLevelOverview = `
    This system is a fully autonomous, end-to-end agentic framework that continuously ingests knowledge, learns from outcomes, and produces high-performance cross-platform social media campaigns with minimal human intervention.

    At the center of the system is the Living Knowledge Base — a continuously updated, fully inspectable record of every content seed, data source, insight, post, and decision made by the framework. It provides complete transparency into agent reasoning, supports human-in-the-loop collaboration, and powers all downstream decisions.

    Knowledge ingestion happens through three complementary pipelines:

    • News Event Seeds — Derived from deep internet research via Perplexity Sonar and ChatGPT Deep Research agents. These processes discover emerging events, consolidate sources, and produce high-quality structured event objects.

    • Trend Seeds — Generated by the Trend Research Agent, which analyzes real-time data from Instagram and Facebook through high-volume scraping tools, identifying viral formats, hashtags, patterns, user clusters, and content archetypes.

    • Ungrounded Seeds — Highly creative, non-news, non-trend “freeform concepts” generated by a dedicated ideation agent. These seeds expand the creative space and allow the system to produce content unconstrained by external events.

    All seeds enter the knowledge base after deduplication, consolidation, and validation.

    The Insights Agent then closes the learning loop. It analyzes engagement metrics, comments, audience behavior, and post-level performance across platforms to produce timestamped insight reports. These insights directly influence strategic planning.

    The Planner Agent synthesizes seeds + insights + budget guardrails to produce a weekly content plan. It determines:
    • which seeds to activate
    • how many posts per seed
    • distribution of videos, images, carousels, reels, and text posts
    • and whether allocations respect global constraints

    The Content Creation Agent executes this plan by generating all required media and copy, pulling contextual data directly from the knowledge base. Media is produced through image/video generation services, stored in Supabase, and formatted for each platform.

    Finally, automated publishers for Instagram and Facebook post completed content on schedule. All outcomes and metrics flow back into the knowledge base, enabling continuous strategic refinement across future cycles.
  `

  const contributions = [
    {
      title: 'Fully Autonomous Multi-Agent Pipeline',
      description:
        'A coordinated network of specialized agents handles ingestion, planning, creation, and publishing — turning social media management into a true end-to-end autonomous system.',
      icon: Brain,
      color: 'from-blue-600 to-cyan-600',
    },
    {
      title: 'Closed-Loop Learning System',
      description:
        'The Insights Agent continuously evaluates real campaign results and feeds structured insight reports back into planning and ideation, making each cycle smarter than the last.',
      icon: RefreshCw,
      color: 'from-purple-600 to-pink-600',
    },
    {
      title: 'High-Fidelity Cross-Platform Intelligence',
      description:
        'Unifies data from Facebook and Instagram into a single knowledge layer, enabling platform-aware strategy, richer analytics, and more effective content decisions.',
      icon: TrendingUp,
      color: 'from-green-600 to-emerald-600',
    },
    {
      title: 'Scalable Parallel Campaigns',
      description:
        'Designed for multi-brand and multi-campaign operation, with content seeds, plans, and content lifecycles that can be segmented and scaled with minimal additional overhead.',
      icon: Target,
      color: 'from-orange-600 to-red-600',
    },
    {
      title: 'Transparent Human-In-The-Loop Control',
      description:
        'The Living Knowledge Base UI exposes every seed, decision, and output so humans can audit, override, or co-create with the agents at any point in the workflow.',
      icon: Users,
      color: 'from-cyan-600 to-blue-600',
    },
  ]

  return (
    <div className="max-w-7xl mx-auto space-y-16">
      {/* Hero Section */}
      <div className="relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-br from-cyan-100/30 via-blue-100/20 to-slate-100/30 rounded-3xl blur-3xl"></div>
        <div className="relative text-center py-16 px-6">
          <div className="flex items-center justify-center gap-3 mb-6">
            <div className="relative">
              <Network className="w-16 h-16 text-cyan-600" />
              <div className="absolute inset-0 blur-xl bg-cyan-400 opacity-40 animate-pulse-slow"></div>
            </div>
          </div>
          <h1 className="text-6xl md:text-7xl font-bold mb-6 text-slate-900">
            BuzzFactory
          </h1>
          <p className="text-2xl font-semibold text-slate-700 mb-4">
            An Agentic Engagement Engine
          </p>
          <p className="text-lg md:text-xl text-slate-600 max-w-4xl mx-auto leading-relaxed">
            An adaptive, learning, end-to-end agentic framework for managing cross-platform social media campaigns
            with intelligent automation, strategic insights, and seamless execution.
          </p>
        </div>
      </div>

      {/* Architecture Diagram */}
      <section>
        <ArchitectureDiagram />
      </section>

      {/* High Level Overview */}
      <section className="bg-white rounded-2xl shadow-xl p-8 border border-slate-200">
        <h2 className="text-3xl font-bold text-slate-900 mb-6 text-center">High Level Overview</h2>
        <div className="prose prose-slate max-w-none">
          <p className="text-slate-700 leading-relaxed whitespace-pre-line">
            {highLevelOverview}
          </p>
        </div>
      </section>

      {/* Important Contributions */}
      <section className="bg-gradient-to-br from-slate-900 to-slate-800 rounded-2xl shadow-2xl p-12 border border-slate-700">
        <h2 className="text-4xl font-bold text-white mb-4 text-center">Important Contributions</h2>
        <p className="text-slate-300 text-center mb-12 text-lg max-w-3xl mx-auto">
          This system represents a significant advancement in autonomous social media management,
          combining cutting-edge AI agents with strategic analytics and seamless platform integration.
        </p>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {contributions.slice(0, 3).map((contribution, index) => (
            <div
              key={index}
              className="group p-6 bg-slate-800/50 backdrop-blur-sm rounded-xl border border-slate-700 hover:border-cyan-500 transition-all duration-300 hover:shadow-xl hover:shadow-cyan-500/20"
            >
              <div className={`inline-flex p-4 rounded-xl bg-gradient-to-br ${contribution.color} mb-4 group-hover:scale-110 transition-transform duration-300`}>
                <contribution.icon className="w-8 h-8 text-white" />
              </div>
              <h3 className="text-xl font-bold text-white mb-3">{contribution.title}</h3>
              <p className="text-slate-300 leading-relaxed">{contribution.description}</p>
            </div>
          ))}
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mt-8 max-w-4xl mx-auto">
          {contributions.slice(3).map((contribution, index) => (
            <div
              key={index}
              className="group p-6 bg-slate-800/50 backdrop-blur-sm rounded-xl border border-slate-700 hover:border-cyan-500 transition-all duration-300 hover:shadow-xl hover:shadow-cyan-500/20"
            >
              <div className={`inline-flex p-4 rounded-xl bg-gradient-to-br ${contribution.color} mb-4 group-hover:scale-110 transition-transform duration-300`}>
                <contribution.icon className="w-8 h-8 text-white" />
              </div>
              <h3 className="text-xl font-bold text-white mb-3">{contribution.title}</h3>
              <p className="text-slate-300 leading-relaxed">{contribution.description}</p>
            </div>
          ))}
        </div>
      </section>
    </div>
  )
}
